boost:
  version: "1_85_0"
  root: "../boost_1_85_0"

algolia:
  app-id: D7O1MLLTAF
  api-key: YourWriteAPIKey

crawlers:
  - name: BoostGraph
    libraries:
      - key: graph
        last-records: 160
        last-words: 118564
        last-lvls: 160

  - name: BoostIostreams
    libraries:
      - key: iostreams
        last-records: 284
        last-words: 34965
        last-lvls: 568

  - name: BoostPreprocessor
    libraries:
      - key: preprocessor
        last-records: 516
        last-words: 79625
        last-lvls: 516

  - name: BoostGIL
    libraries:
      - key: gil
        last-records: 122
        last-words: 25365
        last-lvls: 298

  - name: BoostMPL
    libraries:
      - key: mpl
        last-records: 1628
        last-words: 33772
        last-lvls: 6178

  - name: BoostOutcome
    libraries:
      - key: outcome
        last-records: 435
        last-words: 81029
        last-lvls: 1428

  - name: BoostException
    libraries:
      - key: exception
        last-records: 68
        last-words: 8476
        last-lvls: 68

  - name: BoostTokenizer
    libraries:
      - key: tokenizer
        last-records: 8
        last-words: 3358
        last-lvls: 8

  - name: BoostPolygon
    libraries:
      - key: polygon
        last-records: 32
        last-words: 44526
        last-lvls: 32

  - name: BoostFunctional
    libraries:
      - key: functional
        last-records: 6
        last-words: 3036
        last-lvls: 6

  - name: BoostSerialization
    libraries:
      - key: serialization
        last-records: 176
        last-words: 38015
        last-lvls: 360

  - name: BoostFormat
    libraries:
      - key: format
        last-records: 14
        last-words: 13332
        last-lvls: 17

  - name: Gargoyle
    libraries:
      - key: spirit/classic
        last-records: 54
        last-words: 53194
        last-lvls: 54

      - key: wave
        last-records: 19
        last-words: 20146
        last-lvls: 19

  - name: Helmethead
    libraries:
      - key: graph_parallel
        last-records: 240
        last-words: 28480
        last-lvls: 509

      - key: iterator
        last-records: 212
        last-words: 24462
        last-lvls: 624

      - key: ptr_container
        last-records: 142
        last-words: 15298
        last-lvls: 247

  - name: Harlequin
    libraries:
      - key: numeric/interval
        last-records: 9
        last-words: 14223
        last-lvls: 9

      - key: numeric/ublas
        last-records: 71
        last-words: 44515
        last-lvls: 71

  - name: Tarentola
    libraries:
      - key: parameter
        last-records: 100
        last-words: 25765
        last-lvls: 225

      - key: parameter_python
        last-records: 19
        last-words: 1805
        last-lvls: 29

  - name: FlatPage
    libraries:
      - key: assign
        last-records: 26
        last-words: 4716
        last-lvls: 43

      - key: concept_check
        last-records: 25
        last-words: 5297
        last-lvls: 37

      - key: dynamic_bitset
        last-records: 20
        last-words: 5913
        last-lvls: 20

      - key: filesystem
        last-records: 112
        last-words: 28883
        last-lvls: 245

      - key: flyweight
        last-records: 155
        last-words: 15498
        last-lvls: 232

      - key: multi_index
        last-records: 292
        last-words: 57453
        last-lvls: 541

      - key: property_map
        last-records: 23
        last-words: 6447
        last-lvls: 23

      - key: rational
        last-records: 23
        last-words: 4606
        last-lvls: 34

      - key: statechart
        last-records: 123
        last-words: 27069
        last-lvls: 172

      - key: timer
        last-records: 31
        last-words: 3373
        last-lvls: 50

      - key: uuid
        last-records: 44
        last-words: 3007
        last-lvls: 104

  - name: Doxygen
    libraries:
      - key: hana
        last-records: 428
        last-words: 132821
        last-lvls: 1036

      - key: locale
        last-records: 496
        last-words: 49380
        last-lvls: 1019

      - key: nowide
        last-records: 108
        last-words: 8220
        last-lvls: 200

      - key: redis
        last-records: 88
        last-words: 10660
        last-lvls: 204

  - name: AsciiDoc
    libraries:
      - key: assert
        last-records: 20
        last-words: 1444
        last-lvls: 35

      - key: charconv
        last-records: 81
        last-words: 4059
        last-lvls: 204

      - key: compat
        last-records: 46
        last-words: 1079
        last-lvls: 124

      - key: container_hash
        last-records: 42
        last-words: 6819
        last-lvls: 84

      - key: describe
        last-records: 75
        last-words: 6802
        last-lvls: 169

      - key: endian
        last-records: 91
        last-words: 12179
        last-lvls: 221

      - key: io
        last-records: 42
        last-words: 2637
        last-lvls: 90

      - key: lambda2
        last-records: 23
        last-words: 1749
        last-lvls: 55

      - key: leaf
        last-records: 133
        last-words: 25114
        last-lvls: 287

      - key: mp11
        last-records: 228
        last-words: 13617
        last-lvls: 647

      - key: predef
        last-records: 176
        last-words: 8543
        last-lvls: 471

      - key: qvm
        last-records: 211
        last-words: 18439
        last-lvls: 599

      - key: smart_ptr
        last-records: 293
        last-words: 21784
        last-lvls: 700

      - key: system
        last-records: 116
        last-words: 14054
        last-lvls: 344

      - key: throw_exception
        last-records: 15
        last-words: 1434
        last-lvls: 25

      - key: unordered
        last-records: 1042
        last-words: 78367
        last-lvls: 3782

      - key: variant2
        last-records: 51
        last-words: 6161
        last-lvls: 127

      - key: cobalt
        last-records: 131
        last-words: 14546
        last-lvls: 319

  - name: QuickBook
    libraries:
      - key: accumulators
        last-records: 832
        last-words: 29073
        last-lvls: 2732

      - key: algorithm
        last-records: 439
        last-words: 19835
        last-lvls: 1198

      - key: align
        last-records: 47
        last-words: 2752
        last-lvls: 84

      - key: any
        last-records: 62
        last-words: 3176
        last-lvls: 203

      - key: array
        last-records: 18
        last-words: 1322
        last-lvls: 59

      - key: asio
        last-records: 10214
        last-words: 388055
        last-lvls: 37611

      - key: atomic
        last-records: 74
        last-words: 13467
        last-lvls: 136

      - key: beast
        last-records: 4934
        last-words: 160604
        last-lvls: 18765

      - key: bimap
        last-records: 168
        last-words: 37701
        last-lvls: 414

      - key: bind
        last-records: 64
        last-words: 6396
        last-lvls: 62

      - key: callable_traits
        last-records: 255
        last-words: 10952
        last-lvls: 499

      - key: chrono
        last-records: 369
        last-words: 28121
        last-lvls: 722

      - key: circular_buffer
        last-records: 47
        last-words: 21007
        last-lvls: 105

      - key: compute
        last-records: 754
        last-words: 22952
        last-lvls: 2467

      - key: config
        last-records: 55
        last-words: 15691
        last-lvls: 92

      - key: container
        last-records: 544
        last-words: 95133
        last-lvls: 1913

      - key: context
        last-records: 115
        last-words: 7448
        last-lvls: 276

      - key: contract
        last-records: 421
        last-words: 67602
        last-lvls: 1313

      - key: conversion
        last-records: 10
        last-words: 835
        last-lvls: 14

      - key: convert
        last-records: 134
        last-words: 13788
        last-lvls: 407

      - key: core
        last-records: 363
        last-words: 16414
        last-lvls: 710

      - key: coroutine
        last-records: 116
        last-words: 10402
        last-lvls: 339

      - key: coroutine2
        last-records: 88
        last-words: 7704
        last-lvls: 239

      - key: crc
        last-records: 40
        last-words: 8130
        last-lvls: 113

      - key: date_time
        last-records: 580
        last-words: 29138
        last-lvls: 2027

      - key: detail
        last-records: 2
        last-words: 19
        last-lvls: 1

      - key: dll
        last-records: 112
        last-words: 15079
        last-lvls: 319

      - key: fiber
        last-records: 375
        last-words: 36175
        last-lvls: 977

      - key: foreach
        last-records: 18
        last-words: 2525
        last-lvls: 24

      - key: function
        last-records: 55
        last-words: 6511
        last-lvls: 176

      - key: function_types
        last-records: 59
        last-words: 3524
        last-lvls: 149

      - key: functional/factory
        last-records: 21
        last-words: 1349
        last-lvls: 20

      - key: functional/forward
        last-records: 22
        last-words: 1412
        last-lvls: 21

      - key: functional/overloaded_function
        last-records: 10
        last-words: 1021
        last-lvls: 13

      - key: fusion
        last-records: 1702
        last-words: 45685
        last-lvls: 7006

      - key: geometry
        last-records: 2526
        last-words: 86379
        last-lvls: 10621

      - key: heap
        last-records: 97
        last-words: 8297
        last-lvls: 316

      - key: histogram
        last-records: 469
        last-words: 39505
        last-lvls: 1555

      - key: hof
        last-records: 415
        last-words: 13372
        last-lvls: 1162

      - key: icl
        last-records: 734
        last-words: 43360
        last-lvls: 2712

      - key: integer
        last-records: 68
        last-words: 4410
        last-lvls: 123

      - key: interprocess
        last-records: 794
        last-words: 86042
        last-lvls: 2539

      - key: intrusive
        last-records: 710
        last-words: 148474
        last-lvls: 2409

      - key: json
        last-records: 4085
        last-words: 76169
        last-lvls: 17305

      - key: lambda
        last-records: 63
        last-words: 12935
        last-lvls: 113

      - key: lexical_cast
        last-records: 20
        last-words: 5671
        last-lvls: 32

      - key: local_function
        last-records: 53
        last-words: 12138
        last-lvls: 92

      - key: lockfree
        last-records: 49
        last-words: 5902
        last-lvls: 137

      - key: log
        last-records: 1852
        last-words: 117897
        last-lvls: 8194

      - key: math
        last-records: 1912
        last-words: 346668
        last-lvls: 6732

      - key: metaparse
        last-records: 744
        last-words: 53075
        last-lvls: 1477

      - key: move
        last-records: 209
        last-words: 11270
        last-lvls: 643

      - key: mpi
        last-records: 281
        last-words: 28522
        last-lvls: 941

      - key: msm
        last-records: 180
        last-words: 47416
        last-lvls: 442

      - key: multi_array
        last-records: 29
        last-words: 20129
        last-lvls: 28

      - key: multiprecision
        last-records: 202
        last-words: 67609
        last-lvls: 603

      - key: mysql
        last-records: 2626
        last-words: 83615
        last-lvls: 10440

      - key: numeric/conversion
        last-records: 57
        last-words: 8934
        last-lvls: 102

      - key: numeric/odeint
        last-records: 523
        last-words: 52299
        last-lvls: 1834

      - key: optional
        last-records: 87
        last-words: 16882
        last-lvls: 196

      - key: pfr
        last-records: 128
        last-words: 6932
        last-lvls: 393

      - key: phoenix
        last-records: 208
        last-words: 20468
        last-lvls: 586

      - key: poly_collection
        last-records: 98
        last-words: 13837
        last-lvls: 186

      - key: pool
        last-records: 134
        last-words: 11233
        last-lvls: 465

      - key: process
        last-records: 382
        last-words: 23041
        last-lvls: 1319

      - key: program_options
        last-records: 221
        last-words: 13191
        last-lvls: 803

      - key: property_tree
        last-records: 144
        last-words: 8939
        last-lvls: 482

      - key: proto
        last-records: 974
        last-words: 69074
        last-lvls: 3516

      - key: python
        last-records: 510
        last-words: 45343
        last-lvls: 1301

      - key: random
        last-records: 536
        last-words: 32759
        last-lvls: 2285

      - key: range
        last-records: 653
        last-words: 27195
        last-lvls: 2850

      - key: ratio
        last-records: 72
        last-words: 5764
        last-lvls: 135

      - key: regex
        last-records: 290
        last-words: 49539
        last-lvls: 833

      - key: safe_numerics
        last-records: 171
        last-words: 27133
        last-lvls: 455

      - key: scope
        last-records: 103
        last-words: 16825
        last-lvls: 326

      - key: scope_exit
        last-records: 24
        last-words: 3481
        last-lvls: 39

      - key: signals2
        last-records: 174
        last-words: 15804
        last-lvls: 528

      - key: sort
        last-records: 195
        last-words: 27090
        last-lvls: 761

      - key: spirit
        last-records: 1830
        last-words: 153805
        last-lvls: 7684

      - key: spirit/repository
        last-records: 117
        last-words: 8289
        last-lvls: 418

      - key: stacktrace
        last-records: 47
        last-words: 4395
        last-lvls: 135

      - key: static_assert
        last-records: 8
        last-words: 1284
        last-lvls: 7

      - key: static_string
        last-records: 1219
        last-words: 16337
        last-lvls: 5476

      - key: stl_interfaces
        last-records: 133
        last-words: 16244
        last-lvls: 376

      - key: string_algo
        last-records: 63
        last-words: 8416
        last-lvls: 114

      - key: test
        last-records: 1096
        last-words: 77191
        last-lvls: 4232

      - key: thread
        last-records: 740
        last-words: 63219
        last-lvls: 1464

      - key: tribool
        last-records: 20
        last-words: 1138
        last-lvls: 52

      - key: tti
        last-records: 255
        last-words: 28477
        last-lvls: 629

      - key: tuple
        last-records: 33
        last-words: 4142
        last-lvls: 46

      - key: type_erasure
        last-records: 274
        last-words: 14365
        last-lvls: 910

      - key: type_index
        last-records: 85
        last-words: 6505
        last-lvls: 241

      - key: type_traits
        last-records: 214
        last-words: 46622
        last-lvls: 442

      - key: typeof
        last-records: 24
        last-words: 2654
        last-lvls: 40

      - key: units
        last-records: 991
        last-words: 30380
        last-lvls: 2976

      - key: url
        last-records: 9576
        last-words: 136071
        last-lvls: 37895

      - key: utility
        last-records: 152
        last-words: 18555
        last-lvls: 528

      - key: variant
        last-records: 73
        last-words: 9300
        last-lvls: 168

      - key: vmd
        last-records: 376
        last-words: 47395
        last-lvls: 1021

      - key: winapi
        last-records: 4
        last-words: 972
        last-lvls: 3

      - key: xpressive
        last-records: 505
        last-words: 36029
        last-lvls: 1640

      - key: yap
        last-records: 220
        last-words: 20363
        last-lvls: 666
