boost_version: "1_82_0"
boost_root: "../boost_1_82_0"
crawlers:
  - name: BoostIostreams
    libraries:
      - iostreams

  - name: BoostPreprocessor
    libraries:
      - preprocessor

  - name: BoostGIL
    libraries:
      - gil

  - name: BoostHana
    libraries:
      - hana

  - name: BoostMPL
    libraries:
      - mpl

  - name: BoostOutcome
    libraries:
      - outcome

  - name: BoostException
    libraries:
      - exception

  - name: BoostTokenizer
    libraries:
      - tokenizer

  - name: BoostPolygon
    libraries:
      - polygon

  - name: BoostFunctional
    libraries:
      - functional

  - name: BoostSerialization
    libraries:
      - serialization

  - name: BoostFormat
    libraries:
      - format

  - name: Gargoyle
    libraries:
      - spirit/classic
      - wave

  - name: Helmethead
    libraries:
      - graph_parallel
      - iterator
      - ptr_container

  - name: Harlequin
    libraries:
      - numeric/interval
      - numeric/ublas

  - name: Tarentola
    libraries:
      - parameter
      - parameter_python

  - name: FlatPage
    libraries:
      - assign
      - concept_check
      - dynamic_bitset
      - filesystem
      - flyweight
      - multi_index
      - property_map
      - rational
      - statechart
      - timer
      - uuid

  - name: AsciiDoc
    libraries:
      - assert
      - container_hash
      - describe
      - endian
      - io
      - lambda2
      - leaf
      - mp11
      - predef
      - qvm
      - smart_ptr
      - system
      - throw_exception
      - unordered
      - variant2

  - name: QuickBook
    libraries:
      - accumulators
      - algorithm
      - align
      - any
      - array
      - asio
      - atomic
      - beast
      - bimap
      - bind
      - callable_traits
      - chrono
      - circular_buffer
      - compute
      - config
      - container
      - context
      - contract
      - conversion
      - convert
      - core
      - coroutine
      - coroutine2
      - crc
      - date_time
      - detail
      - dll
      - fiber
      - foreach
      - function
      - function_types
      - functional/factory
      - functional/forward
      - functional/overloaded_function
      - fusion
      - geometry
      - graph
      - heap
      - histogram
      - hof
      - icl
      - integer
      - interprocess
      - intrusive
      - json
      - lambda
      - lexical_cast
      - local_function
      - lockfree
      - log
      - math
      - metaparse
      - move
      - mpi
      - msm
      - multi_array
      - multiprecision
      - mysql
      - numeric/conversion
      - numeric/odeint
      - optional
      - pfr
      - phoenix
      - poly_collection
      - pool
      - process
      - program_options
      - property_tree
      - proto
      - python
      - random
      - range
      - ratio
      - regex
      - safe_numerics
      - scope_exit
      - signals2
      - sort
      - spirit
      - spirit/repository
      - stacktrace
      - static_assert
      - static_string
      - stl_interfaces
      - string_algo
      - test
      - thread
      - tribool
      - tti
      - tuple
      - type_erasure
      - type_index
      - type_traits
      - typeof
      - units
      - url
      - utility
      - variant
      - vmd
      - winapi
      - xpressive
      - yap
