boost:
  version: '1_91_0'
  root: '../boost_1_91_0'
  link: 'https://archives.boost.io/release/1.91.0/source/boost_1_91_0.tar.gz'

website-v2-docs:
  root: '../website-v2-docs/build'
  sections:
    - key: 'contributor-guide'
      name: 'Contributor Guide'
      last-records: 473
      last-words: 55946
      last-lvls: 1606

    - key: 'formal-reviews'
      name: 'Formal Reviews'
      last-records: 63
      last-words: 9435
      last-lvls: 212

    - key: 'user-guide'
      name: 'User Guide'
      last-records: 397
      last-words: 88179
      last-lvls: 1227

algolia:
  app-id: D7O1MLLTAF
  api-key: ALGOLIA_WRITE_API_KEY
  settings:
    minWordSizefor1Typo: 3
    minWordSizefor2Typos: 7
    hitsPerPage: 20
    maxValuesPerFacet: 100
    minProximity: 1
    searchableAttributes:
      - unordered(hierarchy.lvl0)
      - unordered(hierarchy.lvl1)
      - unordered(hierarchy.lvl2)
      - unordered(hierarchy.lvl3)
      - unordered(hierarchy.lvl4)
      - unordered(hierarchy.lvl5)
      - unordered(hierarchy.lvl6)
      - content
    numericAttributesToIndex:
    attributesToRetrieve:
      - hierarchy.lvl0.path
      - hierarchy.lvl1.path
      - hierarchy.lvl2.path
      - hierarchy.lvl3.path
      - hierarchy.lvl4.path
      - hierarchy.lvl5.path
      - hierarchy.lvl6.path
      - library_key
      - library_name
    allowTyposOnNumericTokens: false
    ignorePlurals: true
    camelCaseAttributes:
      - hierarchy
      - content
    advancedSyntax: true
    attributeCriteriaComputedByMinProximity: true
    distinct: true
    unretrievableAttributes:
    optionalWords:
    attributesForFaceting:
      - library_key
    attributesToSnippet:
      - 'content:25'
    attributesToHighlight:
      - hierarchy.lvl0.title
      - hierarchy.lvl1.title
      - hierarchy.lvl2.title
      - hierarchy.lvl3.title
      - hierarchy.lvl4.title
      - hierarchy.lvl5.title
      - hierarchy.lvl6.title
    paginationLimitedTo: 1000
    attributeForDistinct: path
    exactOnSingleWordQuery: attribute
    ranking:
      - words
      - filters
      - typo
      - attribute
      - proximity
      - exact
      - custom
    customRanking:
      - desc(weight.pageRank)
      - desc(weight.level)
      - asc(weight.position)
    separatorsToIndex: '!#()[]{}*+-_一,:;<>?@/\^|%&~£¥$§€`''‘’“”†‡.'
    removeWordsIfNoResults: allOptional
    queryType: prefixLast
    highlightPreTag: <em>
    highlightPostTag: </em>
    typoTolerance: 'false'
    alternativesAsExact:
      - ignorePlurals
      - singleWordSynonym

crawlers:
  - name: BoostGraph
    libraries:
      - key: graph
        last-records: 160
        last-words: 118783
        last-lvls: 160

  - name: BoostIostreams
    libraries:
      - key: iostreams
        last-records: 284
        last-words: 34965
        last-lvls: 568

  - name: BoostJson
    libraries:
      - key: json
        last-records: 526
        last-words: 59710
        last-lvls: 1393

  - name: BoostPreprocessor
    libraries:
      - key: preprocessor
        last-records: 516
        last-words: 79625
        last-lvls: 516

  - name: BoostGIL
    libraries:
      - key: gil
        last-records: 122
        last-words: 25540
        last-lvls: 298

  - name: BoostMPL
    libraries:
      - key: mpl
        last-records: 1628
        last-words: 33772
        last-lvls: 6178

  - name: BoostOutcome
    libraries:
      - key: outcome
        last-records: 450
        last-words: 84127
        last-lvls: 1468

  - name: BoostTokenizer
    libraries:
      - key: tokenizer
        last-records: 8
        last-words: 3358
        last-lvls: 8

  - name: BoostPolygon
    libraries:
      - key: polygon
        last-records: 32
        last-words: 44526
        last-lvls: 32

  - name: BoostFunctional
    libraries:
      - key: functional
        last-records: 6
        last-words: 3036
        last-lvls: 6

  - name: BoostSerialization
    libraries:
      - key: serialization
        last-records: 176
        last-words: 38031
        last-lvls: 360

  - name: BoostFormat
    libraries:
      - key: format
        last-records: 14
        last-words: 13332
        last-lvls: 17

  - name: Gargoyle
    libraries:
      - key: spirit/classic
        last-records: 54
        last-words: 53194
        last-lvls: 54

      - key: wave
        last-records: 19
        last-words: 20146
        last-lvls: 19

  - name: Helmethead
    libraries:
      - key: graph_parallel
        last-records: 240
        last-words: 28499
        last-lvls: 509

      - key: iterator
        last-records: 212
        last-words: 24464
        last-lvls: 624

      - key: ptr_container
        last-records: 142
        last-words: 15298
        last-lvls: 247

  - name: Harlequin
    libraries:
      - key: numeric/interval
        last-records: 9
        last-words: 14223
        last-lvls: 9

      - key: numeric/ublas
        last-records: 71
        last-words: 44515
        last-lvls: 71

  - name: Tarentola
    libraries:
      - key: parameter
        last-records: 100
        last-words: 25765
        last-lvls: 225

      - key: parameter_python
        last-records: 19
        last-words: 1805
        last-lvls: 29

  - name: FlatPage
    libraries:
      - key: assign
        last-records: 26
        last-words: 4716
        last-lvls: 43

      - key: concept_check
        last-records: 25
        last-words: 5294
        last-lvls: 37

      - key: filesystem
        last-records: 111
        last-words: 28650
        last-lvls: 242

      - key: flyweight
        last-records: 163
        last-words: 16183
        last-lvls: 243

      - key: multi_index
        last-records: 285
        last-words: 56551
        last-lvls: 532

      - key: property_map
        last-records: 23
        last-words: 6444
        last-lvls: 23

      - key: rational
        last-records: 23
        last-words: 4606
        last-lvls: 34

      - key: statechart
        last-records: 123
        last-words: 27069
        last-lvls: 172

      - key: timer
        last-records: 31
        last-words: 3373
        last-lvls: 50

      - key: uuid
        last-records: 101
        last-words: 7510
        last-lvls: 257

  - name: Doxygen
    libraries:
      - key: hana
        last-records: 428
        last-words: 132821
        last-lvls: 1036

      - key: locale
        last-records: 490
        last-words: 48604
        last-lvls: 1008

      - key: nowide
        last-records: 100
        last-words: 8008
        last-lvls: 185

  - name: Antora
    libraries:
      - key: decimal
        last-records: 257
        last-words: 31151
        last-lvls: 688

      - key: dynamic_bitset
        last-records: 1224
        last-words: 21577
        last-lvls: 2155

      - key: msm
        last-records: 380
        last-words: 39836
        last-lvls: 1825

      - key: openmethod
        last-records: 1339
        last-words: 24767
        last-lvls: 2374

      - key: redis
        last-records: 1000
        last-words: 28836
        last-lvls: 1723

      - key: unordered
        last-records: 1345
        last-words: 102648
        last-lvls: 7425

      - key: url
        last-records: 6827
        last-words: 116424
        last-lvls: 12651

  - name: AsciiDoc
    libraries:
      - key: array
        last-records: 20
        last-words: 1756
        last-lvls: 45

      - key: assert
        last-records: 21
        last-words: 1467
        last-lvls: 37

      - key: bloom
        last-records: 119
        last-words: 14866
        last-lvls: 329

      - key: charconv
        last-records: 80
        last-words: 3962
        last-lvls: 202

      - key: cobalt
        last-records: 163
        last-words: 17380
        last-lvls: 394

      - key: compat
        last-records: 133
        last-words: 3985
        last-lvls: 309

      - key: container_hash
        last-records: 45
        last-words: 7043
        last-lvls: 91

      - key: describe
        last-records: 76
        last-words: 6908
        last-lvls: 171

      - key: endian
        last-records: 91
        last-words: 12200
        last-lvls: 221

      - key: exception
        last-records: 93
        last-words: 7811
        last-lvls: 230

      - key: hash2
        last-records: 175
        last-words: 17531
        last-lvls: 645

      - key: io
        last-records: 42
        last-words: 2637
        last-lvls: 90

      - key: lambda2
        last-records: 23
        last-words: 1749
        last-lvls: 55

      - key: leaf
        last-records: 139
        last-words: 22372
        last-lvls: 304

      - key: mp11
        last-records: 238
        last-words: 14164
        last-lvls: 672

      - key: predef
        last-records: 177
        last-words: 8575
        last-lvls: 473

      - key: process
        last-records: 44
        last-words: 8932
        last-lvls: 84

      - key: qvm
        last-records: 211
        last-words: 18472
        last-lvls: 599

      - key: smart_ptr
        last-records: 298
        last-words: 21948
        last-lvls: 711

      - key: system
        last-records: 123
        last-words: 14921
        last-lvls: 362

      - key: throw_exception
        last-records: 15
        last-words: 1434
        last-lvls: 25

      - key: variant2
        last-records: 54
        last-words: 6215
        last-lvls: 133

  - name: QuickBook
    libraries:
      - key: accumulators
        last-records: 777
        last-words: 29160
        last-lvls: 2438

      - key: algorithm
        last-records: 436
        last-words: 19773
        last-lvls: 1183

      - key: align
        last-records: 47
        last-words: 2752
        last-lvls: 84

      - key: any
        last-records: 64
        last-words: 3428
        last-lvls: 203

      - key: asio
        last-records: 10536
        last-words: 399511
        last-lvls: 38521

      - key: atomic
        last-records: 82
        last-words: 15984
        last-lvls: 152

      - key: beast
        last-records: 4873
        last-words: 161457
        last-lvls: 18416

      - key: bimap
        last-records: 170
        last-words: 37715
        last-lvls: 418

      - key: bind
        last-records: 64
        last-words: 6396
        last-lvls: 62

      - key: callable_traits
        last-records: 255
        last-words: 10952
        last-lvls: 499

      - key: chrono
        last-records: 369
        last-words: 28121
        last-lvls: 722

      - key: circular_buffer
        last-records: 61
        last-words: 21482
        last-lvls: 151

      - key: compute
        last-records: 800
        last-words: 31790
        last-lvls: 2531

      - key: config
        last-records: 63
        last-words: 16975
        last-lvls: 107

      - key: container
        last-records: 582
        last-words: 101988
        last-lvls: 1994

      - key: context
        last-records: 115
        last-words: 7450
        last-lvls: 276

      - key: contract
        last-records: 409
        last-words: 67612
        last-lvls: 1253

      - key: conversion
        last-records: 10
        last-words: 808
        last-lvls: 14

      - key: convert
        last-records: 130
        last-words: 13858
        last-lvls: 387

      - key: core
        last-records: 385
        last-words: 17471
        last-lvls: 748

      - key: coroutine
        last-records: 116
        last-words: 10402
        last-lvls: 339

      - key: coroutine2
        last-records: 88
        last-words: 7702
        last-lvls: 239

      - key: crc
        last-records: 38
        last-words: 7991
        last-lvls: 103

      - key: date_time
        last-records: 674
        last-words: 31474
        last-lvls: 2243

      - key: detail
        last-records: 2
        last-words: 19
        last-lvls: 1

      - key: dll
        last-records: 65
        last-words: 12466
        last-lvls: 149

      - key: fiber
        last-records: 375
        last-words: 36175
        last-lvls: 977

      - key: foreach
        last-records: 18
        last-words: 2525
        last-lvls: 24

      - key: function
        last-records: 55
        last-words: 6511
        last-lvls: 176

      - key: function_types
        last-records: 59
        last-words: 3524
        last-lvls: 149

      - key: functional/factory
        last-records: 21
        last-words: 1349
        last-lvls: 20

      - key: functional/forward
        last-records: 22
        last-words: 1412
        last-lvls: 21

      - key: functional/overloaded_function
        last-records: 21
        last-words: 1654
        last-lvls: 50

      - key: fusion
        last-records: 1702
        last-words: 45685
        last-lvls: 7006

      - key: geometry
        last-records: 2559
        last-words: 87882
        last-lvls: 10746

      - key: heap
        last-records: 93
        last-words: 8335
        last-lvls: 296

      - key: histogram
        last-records: 453
        last-words: 40304
        last-lvls: 1444

      - key: hof
        last-records: 415
        last-words: 13372
        last-lvls: 1162

      - key: icl
        last-records: 713
        last-words: 43341
        last-lvls: 2610

      - key: integer
        last-records: 68
        last-words: 4410
        last-lvls: 123

      - key: interprocess
        last-records: 757
        last-words: 88188
        last-lvls: 2301

      - key: intrusive
        last-records: 671
        last-words: 148895
        last-lvls: 2142

      - key: lambda
        last-records: 63
        last-words: 12935
        last-lvls: 113

      - key: lexical_cast
        last-records: 21
        last-words: 6416
        last-lvls: 33

      - key: local_function
        last-records: 75
        last-words: 14313
        last-lvls: 166

      - key: lockfree
        last-records: 45
        last-words: 6874
        last-lvls: 113

      - key: log
        last-records: 1782
        last-words: 120255
        last-lvls: 7647

      - key: math
        last-records: 2049
        last-words: 364878
        last-lvls: 7235

      - key: metaparse
        last-records: 744
        last-words: 53075
        last-lvls: 1477

      - key: move
        last-records: 112
        last-words: 9725
        last-lvls: 284

      - key: mpi
        last-records: 182
        last-words: 23947
        last-lvls: 581

      - key: multi_array
        last-records: 29
        last-words: 20134
        last-lvls: 28

      - key: multiprecision
        last-records: 204
        last-words: 68001
        last-lvls: 768

      - key: mysql
        last-records: 3655
        last-words: 133699
        last-lvls: 14254

      - key: mqtt5
        last-records: 629
        last-words: 28491
        last-lvls: 2025

      - key: numeric/conversion
        last-records: 57
        last-words: 8934
        last-lvls: 102

      - key: numeric/odeint
        last-records: 486
        last-words: 52266
        last-lvls: 1649

      - key: optional
        last-records: 92
        last-words: 16191
        last-lvls: 197

      - key: parser
        last-records: 598
        last-words: 63487
        last-lvls: 581

      - key: pfr
        last-records: 131
        last-words: 7263
        last-lvls: 396

      - key: phoenix
        last-records: 208
        last-words: 20468
        last-lvls: 586

      - key: poly_collection
        last-records: 106
        last-words: 16345
        last-lvls: 202

      - key: pool
        last-records: 137
        last-words: 11509
        last-lvls: 471

      - key: program_options
        last-records: 196
        last-words: 12943
        last-lvls: 686

      - key: property_tree
        last-records: 159
        last-words: 9730
        last-lvls: 530

      - key: proto
        last-records: 974
        last-words: 69074
        last-lvls: 3516

      - key: python
        last-records: 510
        last-words: 45343
        last-lvls: 1301

      - key: random
        last-records: 454
        last-words: 34460
        last-lvls: 1892

      - key: range
        last-records: 653
        last-words: 27219
        last-lvls: 2850

      - key: ratio
        last-records: 72
        last-words: 5764
        last-lvls: 135

      - key: regex
        last-records: 287
        last-words: 46585
        last-lvls: 826

      - key: safe_numerics
        last-records: 171
        last-words: 27133
        last-lvls: 455

      - key: scope
        last-records: 99
        last-words: 16967
        last-lvls: 306

      - key: scope_exit
        last-records: 43
        last-words: 5806
        last-lvls: 104

      - key: signals2
        last-records: 175
        last-words: 15839
        last-lvls: 533

      - key: sort
        last-records: 195
        last-words: 27170
        last-lvls: 761

      - key: spirit
        last-records: 1832
        last-words: 154198
        last-lvls: 7689

      - key: spirit/repository
        last-records: 117
        last-words: 8289
        last-lvls: 418

      - key: stacktrace
        last-records: 56
        last-words: 5435
        last-lvls: 152

      - key: static_assert
        last-records: 0
        last-words: 0
        last-lvls: 0

      - key: static_string
        last-records: 1227
        last-words: 17770
        last-lvls: 5505

      - key: stl_interfaces
        last-records: 129
        last-words: 16174
        last-lvls: 356

      - key: string_algo
        last-records: 63
        last-words: 10387
        last-lvls: 114

      - key: test
        last-records: 1004
        last-words: 76692
        last-lvls: 3764

      - key: thread
        last-records: 740
        last-words: 63219
        last-lvls: 1464

      - key: tribool
        last-records: 45
        last-words: 2054
        last-lvls: 142

      - key: tti
        last-records: 255
        last-words: 28475
        last-lvls: 629

      - key: tuple
        last-records: 33
        last-words: 4142
        last-lvls: 46

      - key: type_erasure
        last-records: 237
        last-words: 11630
        last-lvls: 773

      - key: type_index
        last-records: 99
        last-words: 7437
        last-lvls: 284

      - key: type_traits
        last-records: 214
        last-words: 46622
        last-lvls: 442

      - key: typeof
        last-records: 24
        last-words: 2654
        last-lvls: 40

      - key: units
        last-records: 1100
        last-words: 32496
        last-lvls: 3376

      - key: utility
        last-records: 153
        last-words: 19212
        last-lvls: 526

      - key: variant
        last-records: 71
        last-words: 9206
        last-lvls: 161

      - key: vmd
        last-records: 376
        last-words: 47395
        last-lvls: 1021

      - key: winapi
        last-records: 4
        last-words: 972
        last-lvls: 3

      - key: xpressive
        last-records: 501
        last-words: 36130
        last-lvls: 1600

      - key: yap
        last-records: 202
        last-words: 18950
        last-lvls: 600
